# Generated by Django 3.2.4 on 2021-06-28 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, null=True)),
                ('foss', models.TextField(blank=True)),
                ('foss_id', models.IntegerField(blank=True)),
                ('tutorial', models.TextField(blank=True)),
                ('tutorial_id', models.IntegerField(blank=True)),
                ('language', models.TextField(blank=True)),
                ('language_id', models.IntegerField(blank=True)),
                ('suggested_title', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=False)),
                ('data_file', models.FileField(upload_to='scripts')),
                ('ordering', models.TextField(default='')),
                ('published_on', models.DateTimeField(null=True)),
                ('versionNo', models.PositiveIntegerField(null=True)),
                ('editable', models.BooleanField(default=False)),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cue', models.TextField(blank=True)),
                ('narration', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField()),
                ('prevRow', models.PositiveIntegerField(null=True)),
                ('nextRow', models.PositiveIntegerField(null=True)),
                ('comment_status', models.BooleanField(default=False)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptmanager.script')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('done', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('script_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptmanager.scriptdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
