# Generated by Django 3.2.4 on 2021-07-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='outline',
            field=models.TextField(blank=True),
        ),
    ]
